import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
const rubik = Rubik({
  variable: "--rubik",
  subsets: ["latin"],
});

export const metadata = {
  title: "RK Pedia!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} antialiased`}>
          <Header />
          {children}
      </body>
    </html>
  );
}
