import Footer from "../components/footer";
import Header from "../components/header";
import "./globals.css";

export const metadata = {
  title: "R&M Pedia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-[var(--background)]  antialiased `}
      >
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
